# Generated by Django 2.2.2 on 2019-06-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesname', models.TextField()),
                ('findimages', models.ImageField(upload_to='uploadimages/')),
            ],
        ),
    ]
