# Generated by Django 2.2.2 on 2019-06-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190626_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Namecard',
        ),
    ]
